version: '3.9'
name: logger-service
networks:
  logger-service:
    name: logger-service
services:
  app:
    build: .
    image: sing3demons/filesystem:0.1
    container_name: filesystem
    restart: always
    ports:
      - "8080:8080"
    # links:
    #   - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: sing3demons/filesystem:0.1
    volumes:
      - ./imagestore:/imagestore
    networks:
      - logger-service
